before_script:
  - composer self-update
  - composer install --no-interaction --prefer-dist

test:style:
  image: yappabe/php-ci:7.0
  script:
    - vendor/bin/phpcs --standard=psr2 src/
    
test:7.0:
  image: yappabe/php-ci:7.0
  script:
    - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover 
    
test:7.1:
  image: yappabe/php-ci:7.1
  script:
    - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover 

test:7.2:
  image: yappabe/php-ci:7.2
  script:
    - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover 
